spring.application.name=tech_cup
logging.file.name=logs/tech-cup.log

spring.datasource.url=jdbc:postgresql://ep-quiet-lake-antvz9rv.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_LX4Z1ObFhQqA
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=CodeForge
spring.security.user.password=DOSW301