spring.application.name=tech_cup
logging.file.name=/home/LogFiles/spring.log

spring.datasource.url=${DB_URL:jdbc:postgresql://ep-quiet-lake-antvz9rv.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_LX4Z1ObFhQqA}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=CodeForge
spring.security.user.password=DOSW301

server.port=${PORT:80}